{% set version = "3.17.0" %}
{% set sha256 = "10d63069fc8daa93a42659ebf406772dc050b68df607a337b736122931443fbb" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 9f3fe46e5afae6456b1cc8948b23e3d95b44ca50.patch
    - 0001-disable-tests-using-long-file-names.patch  # [not win]
    - 0002-Disable-test-involving-broken-elf.patch

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
    - rm ${SP_DIR}/Orange/tests/binary-blob.tab  # [unix]
    - del /s /q %SP_DIR%\Orange\tests\binary-blob.tab  # [win]
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: True
  skip: True        # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - setuptools    >=36.3
    - scipy         >=0.16.1
    - scikit-learn  >=0.18.1
    - bottleneck    >=1.0.0
    - chardet       >=3.0.2
    - docutils
    - xlrd          >=0.9.2
    - anyqt         >=0.0.8
    - pyqtgraph     >=0.10.0
    - joblib        >=0.9.4
    - keyring
    - keyrings.alt
    - dill
    - pip
    - python.app    # [osx]
    - commonmark    >=0.5.5
    - serverfiles
    - python-louvain
    - matplotlib    >=2.0.0

test:
  commands:
    - orange-canvas --help
    - python -m unittest -v Orange.tests  # [not linux32]
  imports:
    - Orange

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
    - primozgodec
