{% set version = "3.28.0" %}
{% set sha256 = "2484904ae1d087c8fac241c8de2607ecdaabfd33637dd56ca9107d5e4e42492a" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
      #- rm ${SP_DIR}/Orange/tests/binary-blob.tab  # [unix]
      #- del /s /q %SP_DIR%\Orange\tests\binary-blob.tab  # [win]
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: True
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - numpy
    - pip
    - setuptools
    - wheel
    - python
    - recommonmark
    - sphinx
  run:
    # appnope should be in orange-widget-base TODO: add it to next release, or find different solution
    - appnope  # [osx]
    - anyqt >=0.0.11
    - baycomp >=1.0.2
    - bottleneck >=1.0.0
    - chardet >=3.0.2
    - httpx >=0.14.0,<0.17
    - joblib >=0.9.4
    - keyring
    - keyrings.alt
    - matplotlib-base >=2.0.0
    - networkx
    - numpy >=1.16.0
    - openpyxl
    - opentsne >=0.4.3
    - orange-canvas-core >=0.1.19,<0.2a
    - orange-widget-base >=4.12.0
    - pandas >=1.0.0
    - pip >=9.0
    - pyqt >=5.12,!=5.15.1
    - pyqtgraph >=0.11.0
    - pyqtwebengine >=5.12
    - python
    - python-louvain >=0.13
    - pyyaml
    - requests
    - scikit-learn >=0.22.0,!=0.23.0
    - scipy >=0.16.1
    - serverfiles
    - setuptools >=36.3
    - typing  # [py<=34]
    # xgboost is optional since user must install libomp (with brew) on macOS for xgboost to work
    # it is not required for xgboost from conda - it is why I am adding a package to the recipe
    - xgboost
    - catboost  # [not linux and not py39]
    - xlrd >=0.9.2
    - xlsxwriter
    - {{ pin_compatible('numpy') }}
    - python.app  # [osx]


test:
  imports:
    - Orange
    - Orange.canvas
  requires:
    - pip
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
    #- MPLBACKEND=Agg python -m unittest -v Orange.tests  # [not win and not linux32]
    #- python -m unittest -v Orange.tests  # [win]

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
    - primozgodec
    - carlodri
