{% set version = "3.26.0" %}
{% set sha256 = "0814bd19e622816eb37a54ed807c0820c7e6fe543697a2a8a9a5caafe4915db7" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-tweak-import-error-message-to-link-to-Numpy-MKL-trou.patch

build:
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
      #- rm ${SP_DIR}/Orange/tests/binary-blob.tab  # [unix]
      #- del /s /q %SP_DIR%\Orange\tests\binary-blob.tab  # [win]
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: True
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - wheel
    - numpy >=1.13.0
  run:
    - python
    - setuptools >=36.3
    - {{ pin_compatible('numpy') }}
    - scipy >=0.16.1
    - scikit-learn >=0.20.0
    - bottleneck >=1.0.0
    - chardet >=3.0.2
    - docutils
    - xlrd >=0.9.2
    - xlsxwriter
    - anyqt >=0.0.8
    - pyqtgraph >=0.10.0
    - joblib >=0.9.4
    - keyring
    - keyrings.alt
    - pip >=9.0
    - python.app  # [osx]
    - serverfiles
    - python-louvain >=0.13
    - requests
    - matplotlib >=2.0.0
    - openTSNE >=0.3.11
    - pandas
    - pyyaml
#    - fasttsne >=0.2.12
    - orange-canvas-core >=0.1.7,<0.2a
    - orange-widget-base >=4.0a,<4.1a
    - networkx

test:
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
    #- MPLBACKEND=Agg python -m unittest -v Orange.tests  # [not win and not linux32]
    #- python -m unittest -v Orange.tests  # [win]
  imports:
    - Orange

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
    - primozgodec
    - carlodri
