{% set version = "3.4.5" %}
{% set sha256 = "b9a40c20c01ab5f7d01395597e9ac8b6cfd70caa58e4b560c00e91c50a7267f3" %}

package:
  name: orange3
  version: {{ version }}

source:
  fn: Orange3-{{ version }}.tar.gz
  url: https://github.com/biolab/orange3/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - requirements.patch # conda does not yet provide scikit-learn 0.18.1

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: True
  skip: True        # [py2k]

requirements:
  build:
    - toolchain
    - python
    - setuptools
    - numpy x.x
  run:
    - python
    - setuptools
    - numpy x.x
    - numpy         >=1.9.0
    - scipy
    - scikit-learn  >=0.18
    - bottleneck
    - chardet       >=2.3.0
    - docutils
    - xlrd          >=0.9.2
    - anyqt
    - pyqtgraph
    - joblib
    - keyring
    - keyrings.alt
    - dill
    - pip
    - python.app    # [osx]
    - commonmark    >=0.5.5
   
test:
  commands:
    - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    # Linux tests should be reenabled when conda-forge/pyqt-feedstock#19 gets fixed.
    - orange-canvas --help  # [not linux]
  imports:
    - Orange

app:
  entry: orange-canvas
  summary: 'data visualization and data analysis tool'
  icon: icon_48x48.png

about:
  home: http://orange.biolab.si/
  license: GPL3
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: http://orange.biolab.si/docs/
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - astaric
    - lanzagar
    - ales-erjavec
    - nikicc
    - markotoplak
