{% set name = "Orange3" %}
{% set version = "3.36.2" %}

# on our linux builders there is no X11 installed and therefore import
# test will fail
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
{% set enable_testingui = true %}
{% else %}
{% set enable_testingui = false %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Orange3-{{ version }}.tar.gz
  sha256: d436bb98d33aa6ea7b6083359032c704da1a6a0e656c068ce806e2a3f319af8c
  patches:
    - patches/0001-setup.py-Replace-use-of-imp-module.patch

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: True  # [linux and (s390x or ppc64le)]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - patch   # [not win]
    - m2-patch    # [win]
  host:
    - pip
    - python
    - cython
    - docutils
    - numpy
    - recommonmark
    - setuptools
    - sphinx
    - wheel
  run:
    - anyqt >=0.2.0
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    - catboost >=1.0.1
    - chardet >=3.0.2
    - httpx >=0.21.0
    - joblib >=1.0.0
    - keyring
    - keyrings.alt
    - matplotlib-base >=3.2.0
    - networkx
    - numpy >=1.20.0
    - openpyxl
    - opentsne >=0.6.1,!=0.7.0
    - orange-canvas-core >=0.1.30,<0.2a
    - orange-widget-base >=4.22.0
    - pandas >=1.4.0,!=1.5.0,!=2.0.0
    - pip >=18.0
    - pygments >=2.8.0
    - pyqtgraph >=0.13.1
    - python
    - python-louvain >=0.13
    - pyyaml
    - qtconsole >=4.7.2
    - requests
    - scikit-learn >=1.1.0,!=1.2.*,<1.4
    - scipy >=1.9
    - serverfiles
    - setuptools >=51.0.0
    - xgboost >=1.7.4
    - xlrd >=1.2.0
    - xlsxwriter

{% if enable_testingui %}
test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - pip check
    # - python -c "import pkg_resources; pkg_resources.require('Orange3')"
    - orange-canvas --help
    - export QT_QPA_PLATFORM=offscreen  # [not win]
    # no testing on windows ... some widget tests take for ever ...
    # so skip them for windows for now too.
    # - python -m unittest -v Orange.tests Orange.widgets.tests  # [win]
  requires:
    - pip
{% endif %}

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
  type: desk
about:
  home: https://orangedatamining.com/
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: component-based data mining framework
  description: |
    Open source data visualization and data analysis for novice and expert.
    Interactive workflows with a large toolbox.
  doc_url: https://orangedatamining.com/docs
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - lanzagar
    - ales-erjavec
    - markotoplak
    - primozgodec
