{% set name = "Orange3" %}
{% set version = "3.40.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 049564ad26cbc648b6e1a8be430fd640bf35fbbc6693945672056e570f69353d
  patches:
    - patches/0001-remove-upper-bound-for-xgboost-on-osx.patch

build:
  number: 0
  entry_points:
    - orange-canvas = Orange.canvas.__main__:main
  osx_is_app: true
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv
  skip: true  # [py<311]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=3.0
    - numpy {{ numpy }}
    - recommonmark
    - setuptools >=51.0
    - sphinx >=4.2.0,<8
    # In the requirements, but not used from the code
    #- myst-parser
    - wheel
    - trubar >=0.3.4
  run:
    - python
    - baycomp >=1.0.2
    - bottleneck >=1.3.4
    # Encoding detection
    - chardet >=3.0.2
    - httpx >=0.21.0,<1
    # Multiprocessing abstraction
    - joblib >=1.2.0
    - keyring
    # for alternative keyring implementations
    - keyrings.alt
    - networkx
    - numpy >=1.21.0,<2.4
    - openpyxl >=3.1.3
    # 0.7.0 segfaults
    - openTSNE >=0.6.2,!=0.7.0
    - packaging
    - pandas >=2.0.1,<3
    - python-louvain >=0.13
    - pyyaml
    - requests
    - scikit-learn >=1.5.1
    - scipy >=1.9
    # for Data Sets synchronization
    - serverfiles
    # won`t rebuild old xgboost for py313 on osx
    #- xgboost >=1.7.4,<2.1  # [osx]
    - xgboost >=1.7.4
    # Reading Excel files
    - xlrd >=1.2.0
    # Writing Excel Files
    - xlsxwriter
    # Dep to use import Orange
    - orange-canvas-core >=0.2.5,<0.3a
    # Deps to use the orange-canvas script
    - orange-widget-base >=4.25.0
    # Gui deps
    - anyqt >=0.2.0
    - matplotlib-base >=3.2.0
    - pygments >=2.8.0
    - pyqtgraph >=0.13.1
    - qtconsole >=4.7.2

# LINUX
# AssertionError: 'Probability: 19' not found
{% set deselect_tests = " --deselect=Orange.widgets.model.tests.test_owsgd.TestOWSGD.test_minimum_size" %}  # [linux]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_lr" %}  # [linux]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_lr_multiclass" %}  # [linux]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_nb" %}  # [linux]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_nb_multiclass" %}  # [linux]

# OSX
# # AssertionError: 'Probability: 54' not found
{% set deselect_tests = " --deselect=Orange.widgets.utils.tests.test_stickygraphicsview.TestStickyGraphicsView.test" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_lr" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.visualize.tests.test_ownomogram.TestOWNomogram.test_nomogram_nb" %}  # [osx]
# AssertionError: True is not false
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.utils.tests.test_stickygraphicsview.TestStickyGraphicsView.test_fractional_1" %}  # [osx]
{% set deselect_tests = deselect_tests + " --deselect=Orange.widgets.utils.tests.test_stickygraphicsview.TestStickyGraphicsView.test_fractional_2" %}  # [osx]

# WIN
# QMimeDatabase: Error loading internal MIME data
{% set deselect_tests = " --deselect=Orange.widgets.data.tests.test_owcsvimport.TestOWCSVFileImport.test_browse" %}  # [win]
test:
  imports:
    - Orange
    - Orange.canvas
  commands:
    - pip check
    - orange-canvas --help
    - export QT_QPA_PLATFORM=offscreen  # [unix]
    - pytest --pyargs Orange.widgets.tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

app:
  entry: orange-canvas
  summary: data visualization and data analysis tool
  icon: icon_48x48.png
  type: desk
about:
  home: https://orangedatamining.com
  summary: Orange, a component-based data mining framework.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  description: |
    Open source data visualization and data analysis for novice and expert
    Interactive workflows with a large toolbox.
  doc_url: https://orangedatamining.com/docs
  dev_url: https://github.com/biolab/orange3

extra:
  recipe-maintainers:
    - lanzagar
    - ales-erjavec
    - markotoplak
    - primozgodec
  skip-lints:
    - host_section_needs_exact_pinnings
